server:
  port: 8080

jwt:
  key: ${JWT_KEY}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}

files:
  user-photos-dir: ${USER_PHOTOS_DIR}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

      mail.smtp.connectiontimeout: ${MAIL_SMTP_CONNECTION_TIME_OUT}
      mail.smtp.timeout: ${MAIL_SMTP_TIME_OUT}
      mail.smtp.writetimeout: ${MAIL_SMTP_WRITE_TIME_OUT}

  servlet:
    multipart:
      max-file-size: 10MB